apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- namespace.yaml
- rolebinding.yaml


replicas:
- name: productpage
  count: 1
- name: details
  count: 1
- name: ratings
  count: 1
- name: reviews
  count: 1

namespace: bookinfo-dev