apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: pullsecret-cluster-sno02
  namespace: sno02
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pullsecret-cluster-sno02
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: secret/openshiftpullsecret
      property: dockerconfigjson