---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno02
  namespace: sno02
  labels:
    name: sno02
    cloud: hybrid
    cluster-name: 'sno02'
    # Labels for OpenShift Gitops
    cluster.open-cluster-management.io/clusterset: "all-openshift-clusters"
    vendor: "OpenShift"
    # Labels to deploy workload
    app: "webapp"

spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
