apiVersion: v1
kind: PersistentVolume
metadata:
  name: assisted-service-database-storage
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage 
  local:
    path: /dev/vdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-server-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage 
  local:
    path: /dev/vdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-vault-server-1
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem 
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage 
#   local:
#     path: /dev/vdb
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - master
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: data-vault-server-2
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem 
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-storage 
#   local:
#     path: /dev/vdb
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - master