apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo-dev
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: bookinfo-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'bookinfo-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/pandeybk/redhat-ztp-gitops.git
        targetRevision: main
        path: workload/bookinfo/overlays/dev
      destination:
        server: '{{server}}'
        namespace: bookinfo-dev
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
            - CreateNamespace=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: bookinfo-placement
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - webapp