---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno03
  namespace: sno03
  labels:
    name: sno03
    cloud: hybrid
    cluster-name: 'sno03'
    # Labels for OpenShift Gitops
    cluster.open-cluster-management.io/clusterset: "all-openshift-clusters"
    vendor: "OpenShift"
    # Labels to deploy workload
    app: "webapp"
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
