# Creates a ManagedClusterSet resource
#
# Requires:
#   * To associate a cluster to this ManagedClusterSet, add the following label:
#       metadata:
#         labels:
#            cluster.open-cluster-management.io/clusterset: all-openshift-clusters
#            ...
#  

# References:
# https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/applications/managing-applications#register-gitops
# https://github.com/stolostron/multicloud-integrations/tree/main/examples

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSet
metadata:
  name: all-openshift-clusters
spec: {}